import type { Match } from './types'

export const MOCK_MATCHES: Match[] = [
  {
    id: '1',
    sport: 'football',
    homeTeam: {
      id: '1',
      name: 'Arsenal FC',
      shortName: 'ARS',
      logo: 'https://cdn.sofascore.com/images/team/logo/1283.png',
    },
    awayTeam: {
      id: '2',
      name: 'Chelsea FC',
      shortName: 'CHE',
      logo: 'https://cdn.sofascore.com/images/team/logo/1282.png',
    },
    status: 'live',
    startTime: '2026-04-28T14:00:00Z',
    minute: 45,
    league: {
      id: '1',
      name: 'Premier League',
      country: 'England',
      logo: 'https://cdn.sofascore.com/images/league/logo/2.png',
      color: '#3d1959',
    },
    score: {
      home: 2,
      away: 1,
      ht: { home: 1, away: 0 },
    },
    events: [
      {
        type: 'goal',
        minute: 23,
        player: 'Saka',
        team: 'home',
        assist: 'Ødegaard',
      },
      {
        type: 'goal',
        minute: 38,
        player: 'Palmer',
        team: 'away',
      },
      {
        type: 'goal',
        minute: 44,
        player: 'Martinelli',
        team: 'home',
        assist: 'Rice',
      },
      {
        type: 'yellow_card',
        minute: 30,
        player: 'Caicedo',
        team: 'away',
      },
    ],
    streamLinks: [
      { type: 'tv', name: 'Sky Sports' },
      { type: 'stream', name: 'NBC Sports', url: 'https://nbcsports.com' },
    ],
  },
  {
    id: '2',
    sport: 'football',
    homeTeam: {
      id: '3',
      name: 'Real Madrid',
      shortName: 'RMA',
      logo: 'https://cdn.sofascore.com/images/team/logo/1287.png',
    },
    awayTeam: {
      id: '4',
      name: 'FC Barcelona',
      shortName: 'BAR',
      logo: 'https://cdn.sofascore.com/images/team/logo/8634.png',
    },
    status: 'live',
    startTime: '2026-04-28T16:00:00Z',
    minute: 67,
    league: {
      id: '2',
      name: 'La Liga',
      country: 'Spain',
      logo: 'https://cdn.sofascore.com/images/league/logo/8.png',
      color: '#ee8707',
    },
    score: {
      home: 1,
      away: 1,
      ht: { home: 0, away: 1 },
    },
    events: [
      {
        type: 'goal',
        minute: 52,
        player: 'Lewandowski',
        team: 'away',
        assist: 'Pedri',
      },
      {
        type: 'goal',
        minute: 64,
        player: 'Vinicius Jr',
        team: 'home',
      },
    ],
    streamLinks: [
      { type: 'tv', name: 'Movistar+' },
      { type: 'stream', name: 'ESPN', url: 'https://espn.com' },
    ],
  },
  {
    id: '3',
    sport: 'football',
    homeTeam: {
      id: '5',
      name: 'Bayern Munich',
      shortName: 'BAY',
      logo: 'https://cdn.sofascore.com/images/team/logo/1279.png',
    },
    awayTeam: {
      id: '6',
      name: 'Borussia Dortmund',
      shortName: 'DOR',
      logo: 'https://cdn.sofascore.com/images/team/logo/1272.png',
    },
    status: 'upcoming',
    startTime: '2026-04-28T18:30:00Z',
    league: {
      id: '3',
      name: 'Bundesliga',
      country: 'Germany',
      logo: 'https://cdn.sofascore.com/images/league/logo/7.png',
      color: '#e20000',
    },
    score: undefined,
    events: [],
    streamLinks: [
      { type: 'tv', name: 'Sky Bundesliga' },
    ],
  },
  {
    id: '4',
    sport: 'football',
    homeTeam: {
      id: '7',
      name: 'AC Milan',
      shortName: 'MIL',
      logo: 'https://cdn.sofascore.com/images/team/logo/1280.png',
    },
    awayTeam: {
      id: '8',
      name: 'Inter Milan',
      shortName: 'INT',
      logo: 'https://cdn.sofascore.com/images/team/logo/1286.png',
    },
    status: 'finished',
    startTime: '2026-04-28T12:00:00Z',
    league: {
      id: '4',
      name: 'Serie A',
      country: 'Italy',
      logo: 'https://cdn.sofascore.com/images/league/logo/23.png',
      color: '#024f8d',
    },
    score: {
      home: 0,
      away: 2,
      ht: { home: 0, away: 1 },
    },
    events: [
      {
        type: 'goal',
        minute: 35,
        player: 'Lautaro Martinez',
        team: 'away',
      },
      {
        type: 'goal',
        minute: 78,
        player: 'Thuram',
        team: 'away',
        assist: 'Barella',
      },
    ],
    streamLinks: [
      { type: 'tv', name: 'DAZN' },
    ],
  },
  {
    id: '5',
    sport: 'football',
    homeTeam: {
      id: '9',
      name: 'Manchester City',
      shortName: 'MCI',
      logo: 'https://cdn.sofascore.com/images/team/logo/1312.png',
    },
    awayTeam: {
      id: '10',
      name: 'Liverpool FC',
      shortName: 'LIV',
      logo: 'https://cdn.sofascore.com/images/team/logo/1284.png',
    },
    status: 'upcoming',
    startTime: '2026-04-29T16:00:00Z',
    league: {
      id: '1',
      name: 'Premier League',
      country: 'England',
      logo: 'https://cdn.sofascore.com/images/league/logo/2.png',
      color: '#3d1959',
    },
    score: undefined,
    events: [],
    streamLinks: [
      { type: 'tv', name: 'Sky Sports' },
      { type: 'stream', name: 'Peacock', url: 'https://peacocktv.com' },
    ],
  },
  {
    id: '6',
    sport: 'football',
    homeTeam: {
      id: '11',
      name: 'Paris Saint-Germain',
      shortName: 'PSG',
      logo: 'https://cdn.sofascore.com/images/team/logo/1267.png',
    },
    awayTeam: {
      id: '12',
      name: 'Olympique Marseille',
      shortName: 'MAR',
      logo: 'https://cdn.sofascore.com/images/team/logo/1269.png',
    },
    status: 'finished',
    startTime: '2026-04-28T20:45:00Z',
    league: {
      id: '5',
      name: 'Ligue 1',
      country: 'France',
      logo: 'https://cdn.sofascore.com/images/league/logo/5.png',
      color: '#d30f0d',
    },
    score: {
      home: 3,
      away: 1,
      ht: { home: 2, away: 0 },
    },
    events: [
      {
        type: 'goal',
        minute: 12,
        player: 'Dembélé',
        team: 'home',
      },
      {
        type: 'goal',
        minute: 28,
        player: 'Mbappé',
        team: 'home',
        assist: 'Dembélé',
      },
      {
        type: 'goal',
        minute: 55,
        player: 'Harit',
        team: 'away',
      },
      {
        type: 'goal',
        minute: 89,
        player: 'Kang-in Lee',
        team: 'home',
      },
    ],
    streamLinks: [
      { type: 'tv', name: 'Canal+' },
    ],
  },
  {
    id: 'b1',
    sport: 'basketball',
    homeTeam: {
      id: 'b-home1',
      name: 'Los Angeles Lakers',
      shortName: 'LAL',
      logo: 'https://cdn.nba.com/logos/nba/1610612747/global/L/logo.svg',
    },
    awayTeam: {
      id: 'b-away1',
      name: 'Boston Celtics',
      shortName: 'BOS',
      logo: 'https://cdn.nba.com/logos/nba/1610612738/global/L/logo.svg',
    },
    status: 'live',
    startTime: '2026-04-28T19:30:00Z',
    minute: 3,
    league: {
      id: 'b1',
      name: 'NBA',
      country: 'USA',
      logo: 'https://cdn.nba.com/logos/nba/primary/L/logo.svg',
      color: '#1D428A',
    },
    score: {
      home: 15,
      away: 12,
    },
    events: [
      {
        type: 'goal',
        minute: 1,
        player: 'LeBron James',
        team: 'home',
        comment: '3pts',
      },
      {
        type: 'goal',
        minute: 2,
        player: 'Jayson Tatum',
        team: 'away',
        comment: '2pts',
      },
      {
        type: 'goal',
        minute: 3,
        player: 'Anthony Davis',
        team: 'home',
        comment: '3pts',
      },
    ],
    streamLinks: [
      { type: 'tv', name: 'ESPN' },
    ],
  },
  {
    id: 'b2',
    sport: 'basketball',
    homeTeam: {
      id: 'b-home2',
      name: 'Golden State Warriors',
      shortName: 'GSW',
      logo: 'https://cdn.nba.com/logos/nba/1610612744/global/L/logo.svg',
    },
    awayTeam: {
      id: 'b-away2',
      name: 'Miami Heat',
      shortName: 'MIA',
      logo: 'https://cdn.nba.com/logos/nba/1610612748/global/L/logo.svg',
    },
    status: 'upcoming',
    startTime: '2026-04-29T00:00:00Z',
    league: {
      id: 'b1',
      name: 'NBA',
      country: 'USA',
      logo: 'https://cdn.nba.com/logos/nba/primary/L/logo.svg',
      color: '#1D428A',
    },
    score: undefined,
    events: [],
    streamLinks: [
      { type: 'tv', name: 'TNT' },
    ],
  },
  {
    id: 'b3',
    sport: 'basketball',
    homeTeam: {
      id: 'b-home3',
      name: 'Brooklyn Nets',
      shortName: 'BKN',
      logo: 'https://cdn.nba.com/logos/nba/1610612751/global/L/logo.svg',
    },
    awayTeam: {
      id: 'b-away3',
      name: 'Philadelphia 76ers',
      shortName: 'PHI',
      logo: 'https://cdn.nba.com/logos/nba/1610612755/global/L/logo.svg',
    },
    status: 'finished',
    startTime: '2026-04-28T02:00:00Z',
    minute: 48,
    league: {
      id: 'b1',
      name: 'NBA',
      country: 'USA',
      logo: 'https://cdn.nba.com/logos/nba/primary/L/logo.svg',
      color: '#1D428A',
    },
    score: {
      home: 112,
      away: 118,
    },
    events: [
      {
        type: 'goal',
        minute: 10,
        player: 'DeMar DeRozan',
        team: 'home',
        comment: '3pts',
      },
      {
        type: 'goal',
        minute: 20,
        player: 'Giannis Antetokounmpo',
        team: 'away',
        comment: '3pts',
      },
    ],
    streamLinks: [
      { type: 'tv', name: 'NBA League Pass' },
    ],
  },
  {
    id: 'b4',
    sport: 'basketball',
    homeTeam: {
      id: 'b-home4',
      name: 'Chicago Bulls',
      shortName: 'CHI',
      logo: 'https://cdn.nba.com/logos/nba/1610612741/global/L/logo.svg',
    },
    awayTeam: {
      id: 'b-away4',
      name: 'Milwaukee Bucks',
      shortName: 'MIL',
      logo: 'https://cdn.nba.com/logos/nba/1610612749/global/L/logo.svg',
    },
    status: 'live',
    startTime: '2026-04-28T21:00:00Z',
    minute: 8,
    league: {
      id: 'b1',
      name: 'NBA',
      country: 'USA',
      logo: 'https://cdn.nba.com/logos/nba/primary/L/logo.svg',
      color: '#1D428A',
    },
    score: {
      home: 28,
      away: 24,
    },
    events: [
      {
        type: 'goal',
        minute: 4,
        player: 'Stephen Curry',
        team: 'home',
        comment: '3pts',
      },
      {
        type: 'goal',
        minute: 5,
        player: 'Jimmy Butler',
        team: 'away',
        comment: '2pts',
      },
    ],
    streamLinks: [
      { type: 'tv', name: 'ESPN' },
    ],
  },
]