import type { Match } from './types'

export const MOCK_MATCHES: Match[] = [
  {
    id: '1',
    sport: 'football',
    homeTeam: {
      id: '1',
      name: 'Arsenal FC',
      shortName: 'ARS',
      logo: 'https://media.api-sports.io/football/teams/1283.png',
    },
    awayTeam: {
      id: '2',
      name: 'Chelsea FC',
      shortName: 'CHE',
      logo: 'https://media.api-sports.io/football/teams/1282.png',
    },
    status: 'live',
    startTime: '2026-04-28T14:00:00Z',
    minute: 45,
    league: {
      id: '39',
      name: 'Premier League',
      country: 'England',
      logo: 'https://media.api-sports.io/football/leagues/2.png',
      color: '#3d1959',
    },
    score: {
      home: 2,
      away: 1,
      ht: { home: 1, away: 0 },
    },
    events: [
      {
        type: 'goal',
        minute: 23,
        player: 'Saka',
        team: 'home',
        assist: 'Ødegaard',
      },
      {
        type: 'goal',
        minute: 38,
        player: 'Palmer',
        team: 'away',
      },
      {
        type: 'goal',
        minute: 44,
        player: 'Martinelli',
        team: 'home',
        assist: 'Rice',
      },
      {
        type: 'yellow_card',
        minute: 30,
        player: 'Caicedo',
        team: 'away',
      },
    ],
    streamLinks: [
      { type: 'tv', name: 'Sky Sports' },
      { type: 'stream', name: 'NBC Sports', url: 'https://nbcsports.com' },
    ],
  },
  {
    id: '2',
    sport: 'football',
    homeTeam: {
      id: '3',
      name: 'Real Madrid',
      shortName: 'RMA',
      logo: 'https://media.api-sports.io/football/teams/1287.png',
    },
    awayTeam: {
      id: '4',
      name: 'FC Barcelona',
      shortName: 'BAR',
      logo: 'https://media.api-sports.io/football/teams/8634.png',
    },
    status: 'live',
    startTime: '2026-04-28T16:00:00Z',
    minute: 67,
    league: {
      id: '140',
      name: 'La Liga',
      country: 'Spain',
      logo: 'https://media.api-sports.io/football/leagues/8.png',
      color: '#ee8707',
    },
    score: {
      home: 1,
      away: 1,
      ht: { home: 0, away: 1 },
    },
    events: [
      {
        type: 'goal',
        minute: 52,
        player: 'Lewandowski',
        team: 'away',
        assist: 'Pedri',
      },
      {
        type: 'goal',
        minute: 64,
        player: 'Vinicius Jr',
        team: 'home',
      },
    ],
    streamLinks: [
      { type: 'tv', name: 'Movistar+' },
      { type: 'stream', name: 'ESPN', url: 'https://espn.com' },
    ],
  },
  {
    id: '3',
    sport: 'football',
    homeTeam: {
      id: '5',
      name: 'Bayern Munich',
      shortName: 'BAY',
      logo: 'https://media.api-sports.io/football/teams/1279.png',
    },
    awayTeam: {
      id: '6',
      name: 'Borussia Dortmund',
      shortName: 'DOR',
      logo: 'https://media.api-sports.io/football/teams/1272.png',
    },
    status: 'upcoming',
    startTime: '2026-04-28T18:30:00Z',
    league: {
      id: '78',
      name: 'Bundesliga',
      country: 'Germany',
      logo: 'https://media.api-sports.io/football/leagues/7.png',
      color: '#e20000',
    },
    score: undefined,
    events: [],
    streamLinks: [
      { type: 'tv', name: 'Sky Bundesliga' },
    ],
  },
  {
    id: '4',
    sport: 'football',
    homeTeam: {
      id: '7',
      name: 'AC Milan',
      shortName: 'MIL',
      logo: 'https://media.api-sports.io/football/teams/1280.png',
    },
    awayTeam: {
      id: '8',
      name: 'Inter Milan',
      shortName: 'INT',
      logo: 'https://media.api-sports.io/football/teams/1286.png',
    },
    status: 'finished',
    startTime: '2026-04-28T12:00:00Z',
    league: {
      id: '135',
      name: 'Serie A',
      country: 'Italy',
      logo: 'https://media.api-sports.io/football/leagues/23.png',
      color: '#024f8d',
    },
    score: {
      home: 0,
      away: 2,
      ht: { home: 0, away: 1 },
    },
    events: [
      {
        type: 'goal',
        minute: 35,
        player: 'Lautaro Martinez',
        team: 'away',
      },
      {
        type: 'goal',
        minute: 78,
        player: 'Thuram',
        team: 'away',
        assist: 'Barella',
      },
    ],
    streamLinks: [
      { type: 'tv', name: 'DAZN' },
    ],
  },
  {
    id: '5',
    sport: 'football',
    homeTeam: {
      id: '9',
      name: 'Manchester City',
      shortName: 'MCI',
      logo: 'https://media.api-sports.io/football/teams/1312.png',
    },
    awayTeam: {
      id: '10',
      name: 'Liverpool FC',
      shortName: 'LIV',
      logo: 'https://media.api-sports.io/football/teams/1284.png',
    },
    status: 'upcoming',
    startTime: '2026-04-29T16:00:00Z',
    league: {
      id: '39',
      name: 'Premier League',
      country: 'England',
      logo: 'https://media.api-sports.io/football/leagues/2.png',
      color: '#3d1959',
    },
    score: undefined,
    events: [],
    streamLinks: [
      { type: 'tv', name: 'Sky Sports' },
      { type: 'stream', name: 'Peacock', url: 'https://peacocktv.com' },
    ],
  },
  {
    id: '6',
    sport: 'football',
    homeTeam: {
      id: '11',
      name: 'Paris Saint-Germain',
      shortName: 'PSG',
      logo: 'https://media.api-sports.io/football/teams/1267.png',
    },
    awayTeam: {
      id: '12',
      name: 'Olympique Marseille',
      shortName: 'MAR',
      logo: 'https://media.api-sports.io/football/teams/1269.png',
    },
    status: 'finished',
    startTime: '2026-04-28T20:45:00Z',
    league: {
      id: '61',
      name: 'Ligue 1',
      country: 'France',
      logo: 'https://media.api-sports.io/football/leagues/5.png',
      color: '#d30f0d',
    },
    score: {
      home: 3,
      away: 1,
      ht: { home: 2, away: 0 },
    },
    events: [
      {
        type: 'goal',
        minute: 12,
        player: 'Dembélé',
        team: 'home',
      },
      {
        type: 'goal',
        minute: 28,
        player: 'Mbappé',
        team: 'home',
        assist: 'Dembélé',
      },
      {
        type: 'goal',
        minute: 55,
        player: 'Harit',
        team: 'away',
      },
      {
        type: 'goal',
        minute: 89,
        player: 'Kang-in Lee',
        team: 'home',
      },
    ],
    streamLinks: [
      { type: 'tv', name: 'Canal+' },
    ],
  },
  {
    id: 'b1',
    sport: 'basketball',
    homeTeam: {
      id: 'b-home1',
      name: 'Los Angeles Lakers',
      shortName: 'LAL',
      logo: 'https://cdn.nba.com/logos/nba/1610612747/global/L/logo.svg',
    },
    awayTeam: {
      id: 'b-away1',
      name: 'Boston Celtics',
      shortName: 'BOS',
      logo: 'https://cdn.nba.com/logos/nba/1610612738/global/L/logo.svg',
    },
    status: 'live',
    startTime: '2026-04-28T19:30:00Z',
    minute: 3,
    league: {
      id: 'b1',
      name: 'NBA',
      country: 'USA',
      logo: 'https://cdn.nba.com/logos/nba/primary/L/logo.svg',
      color: '#1D428A',
    },
    score: {
      home: 15,
      away: 12,
    },
    events: [
      {
        type: 'goal',
        minute: 1,
        player: 'LeBron James',
        team: 'home',
        comment: '3pts',
      },
      {
        type: 'goal',
        minute: 2,
        player: 'Jayson Tatum',
        team: 'away',
        comment: '2pts',
      },
      {
        type: 'goal',
        minute: 3,
        player: 'Anthony Davis',
        team: 'home',
        comment: '3pts',
      },
    ],
    streamLinks: [
      { type: 'tv', name: 'ESPN' },
    ],
  },
  {
    id: 'b2',
    sport: 'basketball',
    homeTeam: {
      id: 'b-home2',
      name: 'Golden State Warriors',
      shortName: 'GSW',
      logo: 'https://cdn.nba.com/logos/nba/1610612744/global/L/logo.svg',
    },
    awayTeam: {
      id: 'b-away2',
      name: 'Miami Heat',
      shortName: 'MIA',
      logo: 'https://cdn.nba.com/logos/nba/1610612748/global/L/logo.svg',
    },
    status: 'upcoming',
    startTime: '2026-04-29T00:00:00Z',
    league: {
      id: 'b1',
      name: 'NBA',
      country: 'USA',
      logo: 'https://cdn.nba.com/logos/nba/primary/L/logo.svg',
      color: '#1D428A',
    },
    score: undefined,
    events: [],
    streamLinks: [
      { type: 'tv', name: 'TNT' },
    ],
  },
  {
    id: 'b3',
    sport: 'basketball',
    homeTeam: {
      id: 'b-home3',
      name: 'Brooklyn Nets',
      shortName: 'BKN',
      logo: 'https://cdn.nba.com/logos/nba/1610612751/global/L/logo.svg',
    },
    awayTeam: {
      id: 'b-away3',
      name: 'Philadelphia 76ers',
      shortName: 'PHI',
      logo: 'https://cdn.nba.com/logos/nba/1610612755/global/L/logo.svg',
    },
    status: 'finished',
    startTime: '2026-04-28T02:00:00Z',
    minute: 48,
    league: {
      id: 'b1',
      name: 'NBA',
      country: 'USA',
      logo: 'https://cdn.nba.com/logos/nba/primary/L/logo.svg',
      color: '#1D428A',
    },
    score: {
      home: 112,
      away: 118,
    },
    events: [
      {
        type: 'goal',
        minute: 10,
        player: 'DeMar DeRozan',
        team: 'home',
        comment: '3pts',
      },
      {
        type: 'goal',
        minute: 20,
        player: 'Giannis Antetokounmpo',
        team: 'away',
        comment: '3pts',
      },
    ],
    streamLinks: [
      { type: 'tv', name: 'NBA League Pass' },
    ],
  },
  {
    id: 'b4',
    sport: 'basketball',
    homeTeam: {
      id: 'b-home4',
      name: 'Chicago Bulls',
      shortName: 'CHI',
      logo: 'https://cdn.nba.com/logos/nba/1610612741/global/L/logo.svg',
    },
    awayTeam: {
      id: 'b-away4',
      name: 'Milwaukee Bucks',
      shortName: 'MIL',
      logo: 'https://cdn.nba.com/logos/nba/1610612749/global/L/logo.svg',
    },
    status: 'live',
    startTime: '2026-04-28T21:00:00Z',
    minute: 8,
    league: {
      id: 'b1',
      name: 'NBA',
      country: 'USA',
      logo: 'https://cdn.nba.com/logos/nba/primary/L/logo.svg',
      color: '#1D428A',
    },
    score: {
      home: 28,
      away: 24,
    },
    events: [
      {
        type: 'goal',
        minute: 4,
        player: 'Stephen Curry',
        team: 'home',
        comment: '3pts',
      },
      {
        type: 'goal',
        minute: 5,
        player: 'Jimmy Butler',
        team: 'away',
        comment: '2pts',
      },
    ],
    streamLinks: [
      { type: 'tv', name: 'ESPN' },
    ],
  },
]

export const MOCK_BASKETBALL_MATCHES = [
  {
    id: 'b1',
    sport: 'basketball' as const,
    homeTeam: {
      id: 'b-home1',
      name: 'Los Angeles Lakers',
      shortName: 'LAL',
      logo: 'https://cdn.nba.com/logos/nba/1610612747/global/L/logo.svg',
    },
    awayTeam: {
      id: 'b-away1',
      name: 'Boston Celtics',
      shortName: 'BOS',
      logo: 'https://cdn.nba.com/logos/nba/1610612738/global/L/logo.svg',
    },
    status: 'live' as const,
    startTime: '2026-04-28T19:30:00Z',
    minute: 3,
    league: {
      id: 'b1',
      name: 'NBA',
      country: 'USA',
      logo: 'https://cdn.nba.com/logos/nba/primary/L/logo.svg',
      color: '#1D428A',
    },
    score: {
      home: 15,
      away: 12,
      quarters: [
        { home: 15, away: 12 },
      ],
    },
    events: [
      {
        id: 'e1',
        type: 'triple',
        minute: 1,
        player: 'LeBron James',
        team: 'home' as const,
        comment: '3pts',
      },
      {
        id: 'e2',
        type: 'two_pointer',
        minute: 2,
        player: 'Jayson Tatum',
        team: 'away' as const,
        comment: '2pts',
      },
      {
        id: 'e3',
        type: 'triple',
        minute: 3,
        player: 'Anthony Davis',
        team: 'home' as const,
        comment: '3pts',
      },
      {
        id: 'e4',
        type: 'foul',
        minute: 2,
        player: 'Jaylen Brown',
        team: 'away' as const,
        comment: 'Personal foul',
      },
    ],
    streamLinks: [
      { type: 'tv' as const, name: 'ESPN' },
      { type: 'stream' as const, name: 'NBA League Pass', url: 'https://nba.leaguepass.nba.com' },
    ],
  },
  {
    id: 'b2',
    sport: 'basketball' as const,
    homeTeam: {
      id: 'b-home2',
      name: 'Golden State Warriors',
      shortName: 'GSW',
      logo: 'https://cdn.nba.com/logos/nba/1610612744/global/L/logo.svg',
    },
    awayTeam: {
      id: 'b-away2',
      name: 'Miami Heat',
      shortName: 'MIA',
      logo: 'https://cdn.nba.com/logos/nba/1610612748/global/L/logo.svg',
    },
    status: 'live' as const,
    startTime: '2026-04-28T21:00:00Z',
    minute: 8,
    league: {
      id: 'b1',
      name: 'NBA',
      country: 'USA',
      logo: 'https://cdn.nba.com/logos/nba/primary/L/logo.svg',
      color: '#1D428A',
    },
    score: {
      home: 28,
      away: 24,
      quarters: [
        { home: 28, away: 24 },
      ],
    },
    events: [
      {
        id: 'e5',
        type: 'triple',
        minute: 4,
        player: 'Stephen Curry',
        team: 'home' as const,
        comment: '3pts',
      },
      {
        id: 'e6',
        type: 'two_pointer',
        minute: 5,
        player: 'Jimmy Butler',
        team: 'away' as const,
        comment: '2pts',
      },
      {
        id: 'e7',
        type: 'assist',
        minute: 4,
        player: 'Draymond Green',
        team: 'home' as const,
        assist: 'Stephen Curry',
        comment: 'Assist',
      },
      {
        id: 'e8',
        type: 'freethrow',
        minute: 6,
        player: 'Bam Adebayo',
        team: 'away' as const,
        comment: '1/2 FT',
      },
      {
        id: 'e9',
        type: 'rebound',
        minute: 7,
        player: 'Kevon Looney',
        team: 'home' as const,
        comment: 'Defensive rebound',
      },
      {
        id: 'e10',
        type: 'turnover',
        minute: 8,
        player: 'Tyler Herro',
        team: 'away' as const,
        comment: 'Lost ball',
      },
    ],
    streamLinks: [
      { type: 'tv' as const, name: 'TNT' },
      { type: 'stream' as const, name: 'NBA League Pass', url: 'https://nba.leaguepass.nba.com' },
    ],
  },
  {
    id: 'b3',
    sport: 'basketball' as const,
    homeTeam: {
      id: 'b-home3',
      name: 'Brooklyn Nets',
      shortName: 'BKN',
      logo: 'https://cdn.nba.com/logos/nba/1610612751/global/L/logo.svg',
    },
    awayTeam: {
      id: 'b-away3',
      name: 'Philadelphia 76ers',
      shortName: 'PHI',
      logo: 'https://cdn.nba.com/logos/nba/1610612755/global/L/logo.svg',
    },
    status: 'upcoming' as const,
    startTime: '2026-04-29T00:00:00Z',
    league: {
      id: 'b1',
      name: 'NBA',
      country: 'USA',
      logo: 'https://cdn.nba.com/logos/nba/primary/L/logo.svg',
      color: '#1D428A',
    },
    score: undefined,
    events: [],
    streamLinks: [
      { type: 'tv' as const, name: 'ESPN' },
    ],
  },
  {
    id: 'b4',
    sport: 'basketball' as const,
    homeTeam: {
      id: 'b-home4',
      name: 'Chicago Bulls',
      shortName: 'CHI',
      logo: 'https://cdn.nba.com/logos/nba/1610612741/global/L/logo.svg',
    },
    awayTeam: {
      id: 'b-away4',
      name: 'Milwaukee Bucks',
      shortName: 'MIL',
      logo: 'https://cdn.nba.com/logos/nba/1610612749/global/L/logo.svg',
    },
    status: 'finished' as const,
    startTime: '2026-04-28T02:00:00Z',
    minute: 48,
    league: {
      id: 'b1',
      name: 'NBA',
      country: 'USA',
      logo: 'https://cdn.nba.com/logos/nba/primary/L/logo.svg',
      color: '#1D428A',
    },
    score: {
      home: 112,
      away: 118,
      quarters: [
        { home: 28, away: 30 },
        { home: 24, away: 29 },
        { home: 32, away: 28 },
        { home: 28, away: 31 },
      ],
      ht: { home: 52, away: 59 },
    },
    events: [
      {
        id: 'e11',
        type: 'triple',
        minute: 10,
        player: 'DeMar DeRozan',
        team: 'home' as const,
        comment: '3pts',
      },
      {
        id: 'e12',
        type: 'triple',
        minute: 20,
        player: 'Giannis Antetokounmpo',
        team: 'away' as const,
        comment: '3pts',
      },
      {
        id: 'e13',
        type: 'two_pointer',
        minute: 34,
        player: 'Damian Lillard',
        team: 'home' as const,
        comment: '2pts',
      },
      {
        id: 'e14',
        type: 'block',
        minute: 41,
        player: 'Brook Lopez',
        team: 'away' as const,
        comment: 'Blocked shot',
      },
      {
        id: 'e15',
        type: 'steal',
        minute: 45,
        player: 'Jrue Holiday',
        team: 'away' as const,
        comment: 'Steal',
      },
    ],
    streamLinks: [
      { type: 'tv' as const, name: 'NBA League Pass' },
    ],
  },
]

export const MOCK_MMA_MATCHES = [
  {
    id: 'mma1',
    sport: 'mma' as const,
    homeTeam: {
      id: 'mma-home1',
      name: 'Islam Makhachev',
      shortName: 'IM',
      logo: '',
      nickname: 'The Eagle',
    },
    awayTeam: {
      id: 'mma-away1',
      name: 'Dustin Poirier',
      shortName: 'DP',
      logo: '',
      nickname: 'The Diamond',
    },
    status: 'live' as const,
    startTime: '2026-04-28T22:00:00Z',
    minute: 1,
    league: {
      id: 'mma1',
      name: 'UFC',
      country: 'USA',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Ultimate_Fighting_Championship_logo.svg/512px-Ultimate_Fighting_Championship_logo.svg.png',
      color: '#B90000',
    },
    score: { home: 0, away: 0 },
    events: [
      {
        id: 'mma-e1',
        type: 'start',
        minute: 0,
        player: 'Islam Makhachev',
        team: 'home' as const,
        comment: 'Fight started',
      },
    ],
    streamLinks: [
      { type: 'tv' as const, name: 'ESPN+ PPV' },
    ],
  },
  {
    id: 'mma2',
    sport: 'mma' as const,
    homeTeam: {
      id: 'mma-home2',
      name: 'Alex Pereira',
      shortName: 'AP',
      logo: '',
      nickname: 'Poison',
    },
    awayTeam: {
      id: 'mma-away2',
      name: 'Jamahal Hill',
      shortName: 'JH',
      logo: '',
      nickname: 'Sweet Dreams',
    },
    status: 'finished' as const,
    startTime: '2026-04-28T20:00:00Z',
    minute: 25,
    league: {
      id: 'mma1',
      name: 'UFC',
      country: 'USA',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Ultimate_Fighting_Championship_logo.svg/512px-Ultimate_Fighting_Championship_logo.svg.png',
      color: '#B90000',
    },
    score: { home: 1, away: 0 },
    events: [
      {
        id: 'mma-e2',
        type: 'knockout',
        minute: 5,
        player: 'Alex Pereira',
        team: 'home' as const,
        comment: 'Knockout - Round 1 at 2:35',
      },
    ],
    streamLinks: [
      { type: 'tv' as const, name: 'ESPN+ PPV' },
    ],
  },
  {
    id: 'mma3',
    sport: 'mma' as const,
    homeTeam: {
      id: 'mma-home3',
      name: 'Julianna Pena',
      shortName: 'JP',
      logo: '',
      nickname: 'The Venezuelan Vixen',
    },
    awayTeam: {
      id: 'mma-away3',
      name: 'Amanda Nunes',
      shortName: 'AN',
      logo: '',
      nickname: 'The Lioness',
    },
    status: 'upcoming' as const,
    startTime: '2026-04-29T02:00:00Z',
    league: {
      id: 'mma1',
      name: 'UFC',
      country: 'USA',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Ultimate_Fighting_Championship_logo.svg/512px-Ultimate_Fighting_Championship_logo.svg.png',
      color: '#B90000',
    },
    score: undefined,
    events: [],
    streamLinks: [
      { type: 'stream' as const, name: 'ESPN+', url: 'https://espn.com/espnplus' },
    ],
  },
  {
    id: 'mma4',
    sport: 'mma' as const,
    homeTeam: {
      id: 'mma-home4',
      name: 'Charles Oliveira',
      shortName: 'CO',
      logo: '',
      nickname: 'Do Bronx',
    },
    awayTeam: {
      id: 'mma-away4',
      name: 'Arman Tsarukyan',
      shortName: 'AT',
      logo: '',
      nickname: 'The Armenian Tiger',
    },
    status: 'finished' as const,
    startTime: '2026-04-28T18:00:00Z',
    minute: 15,
    league: {
      id: 'mma2',
      name: 'UFC',
      country: 'USA',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Ultimate_Fighting_Championship_logo.svg/512px-Ultimate_Fighting_Championship_logo.svg.png',
      color: '#B90000',
    },
    score: { home: 1, away: 0 },
    events: [
      {
        id: 'mma-e3',
        type: 'submission',
        minute: 3,
        player: 'Charles Oliveira',
        team: 'home' as const,
        comment: 'Submission - Round 3 at 4:12 (Rear Naked Choke)',
      },
    ],
    streamLinks: [
      { type: 'tv' as const, name: 'ESPN+ PPV' },
    ],
  },
]